project:
  type: website

website:
  title: "site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - KNN_and_XGB.ipynb
      - LogisticRegression.ipynb
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



