project:
  type: website

website:
  title: "site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - KNN_and_XGB.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



